# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.17.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.17.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/amaali/learn/c++/urldedupe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/amaali/learn/c++/urldedupe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.17.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.17.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/amaali/learn/c++/urldedupe/CMakeFiles /Users/amaali/learn/c++/urldedupe/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/amaali/learn/c++/urldedupe/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named urldedupe

# Build rule for target.
urldedupe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 urldedupe
.PHONY : urldedupe

# fast build rule for target.
urldedupe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/urldedupe.dir/build.make CMakeFiles/urldedupe.dir/build
.PHONY : urldedupe/fast

Url.o: Url.cpp.o

.PHONY : Url.o

# target to build an object file
Url.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/urldedupe.dir/build.make CMakeFiles/urldedupe.dir/Url.cpp.o
.PHONY : Url.cpp.o

Url.i: Url.cpp.i

.PHONY : Url.i

# target to preprocess a source file
Url.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/urldedupe.dir/build.make CMakeFiles/urldedupe.dir/Url.cpp.i
.PHONY : Url.cpp.i

Url.s: Url.cpp.s

.PHONY : Url.s

# target to generate assembly for a file
Url.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/urldedupe.dir/build.make CMakeFiles/urldedupe.dir/Url.cpp.s
.PHONY : Url.cpp.s

flags.o: flags.cpp.o

.PHONY : flags.o

# target to build an object file
flags.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/urldedupe.dir/build.make CMakeFiles/urldedupe.dir/flags.cpp.o
.PHONY : flags.cpp.o

flags.i: flags.cpp.i

.PHONY : flags.i

# target to preprocess a source file
flags.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/urldedupe.dir/build.make CMakeFiles/urldedupe.dir/flags.cpp.i
.PHONY : flags.cpp.i

flags.s: flags.cpp.s

.PHONY : flags.s

# target to generate assembly for a file
flags.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/urldedupe.dir/build.make CMakeFiles/urldedupe.dir/flags.cpp.s
.PHONY : flags.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/urldedupe.dir/build.make CMakeFiles/urldedupe.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/urldedupe.dir/build.make CMakeFiles/urldedupe.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/urldedupe.dir/build.make CMakeFiles/urldedupe.dir/main.cpp.s
.PHONY : main.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/urldedupe.dir/build.make CMakeFiles/urldedupe.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/urldedupe.dir/build.make CMakeFiles/urldedupe.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/urldedupe.dir/build.make CMakeFiles/urldedupe.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... urldedupe"
	@echo "... Url.o"
	@echo "... Url.i"
	@echo "... Url.s"
	@echo "... flags.o"
	@echo "... flags.i"
	@echo "... flags.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

